-- ----------------------------
-- Table structure for cst
-- ----------------------------

CREATE TABLE `cst` (
  `CST_CODIGO` int(11) NOT NULL AUTO_INCREMENT,
  `CST_CST` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `CST_DESCRICAO` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `CST_ATIVO` enum('S','N') CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT 'S' COMMENT 'S-SIM N-NAO',
  PRIMARY KEY (`CST_CODIGO`)
) ENGINE=InnoDB AUTO_INCREMENT=12 COMMENT='Cadastro de CST';

-- ----------------------------
-- Records of cst
-- ----------------------------
INSERT INTO `cst` VALUES ('1', '00', 'TRIBUTADA INTEGRALMENTE.', 'S');
INSERT INTO `cst` VALUES ('2', '10', 'TRIBUTADA E COM COBRANÇA DO ICMS POR SUBSTITUIÇÃO TRIBUTÁRIA', 'S');
INSERT INTO `cst` VALUES ('3', '20', 'COM REDUÇÃO DE BASE DE CÁLCULO', 'S');
INSERT INTO `cst` VALUES ('4', '30', 'ISENTA OU NÃO TRIBUTADA E COM COBRANÇA DO ICMS POR SUBSTITUIÇÃO TRIBUTÁRIA', 'S');
INSERT INTO `cst` VALUES ('5', '40', 'ISENTA', 'S');
INSERT INTO `cst` VALUES ('6', '41', 'NÃO TRIBUTADA', 'S');
INSERT INTO `cst` VALUES ('7', '50', 'SUSPENSÃO', 'S');
INSERT INTO `cst` VALUES ('8', '51', 'DIFERIMENTO', 'S');
INSERT INTO `cst` VALUES ('9', '60', 'ICMS COBRADO ANTERIORMENTE POR SUBSTITUIÇÃO TRIBUTÁRIA', 'S');
INSERT INTO `cst` VALUES ('10', '70', 'COM REDUÇÃO DE BASE DE CÁLCULO E COBRANÇA DO ICMS POR SUBSTITUIÇÃO TRIBUTÁRIA', 'S');
INSERT INTO `cst` VALUES ('11', '90', 'OUTRAS', 'S');
