-- ----------------------------
-- Table structure for origem_cst
-- ----------------------------

CREATE TABLE `origem_cst` (
  `ORICST_COD` int(11) NOT NULL AUTO_INCREMENT,
  `ORICST_COD_ORIGEM` varchar(1) DEFAULT NULL,
  `ORICST_DESCRICAO_ORIGEM` varchar(250) DEFAULT NULL,
  PRIMARY KEY (`ORICST_COD`)
) ENGINE=InnoDB AUTO_INCREMENT=10;

-- ----------------------------
-- Records of origem_cst
-- ----------------------------
INSERT INTO `origem_cst` VALUES ('1', '0', 'NACIONAL, EXCETO AS INDICADAS NOS CÓDIGOS 3 A 5 E 8.');
INSERT INTO `origem_cst` VALUES ('2', '1', 'ESTRANGEIRA - IMPORTAÇÃO DIRETA, EXCETO A INDICADA NO CÓDIGO 6.');
INSERT INTO `origem_cst` VALUES ('3', '2', 'ESTRANGEIRA - ADQUIRIDA NO MERCADO INTERNO, EXCETO A INDICADA NO CÓDIGO 7.');
INSERT INTO `origem_cst` VALUES ('4', '3', 'NACIONAL, MERCADORIA OU BEM COM CONTEÚDO DE IMPORTAÇÃO SUPERIOR A 40% E INFERIOR OU IGUAL A 70%.');
INSERT INTO `origem_cst` VALUES ('5', '4', 'NACIONAL, CUJA PRODUÇÃO TENHA SIDO FEITA EM CONFORMIDADE COM OS PROCESSOS PRODUTIVOS DE ACORDO COM O DECR. LEI 288/67.');
INSERT INTO `origem_cst` VALUES ('6', '5', 'NACIONAL, MERCADORIA OU BEM COM CONTEÚDO DE IMPORTAÇÃO INFERIOR OU IGUAL A 40%.');
INSERT INTO `origem_cst` VALUES ('7', '6', 'ESTRANGEIRA - IMPORTAÇÃO DIRETA, SEM SIMILAR NACIONAL, CONSTANTE EM LISTA DE RESOLUÇÃO CAMEX E GÁS NATURAL.');
INSERT INTO `origem_cst` VALUES ('8', '7', 'ESTRANGEIRA - ADQUIRIDA NO MERCADO INTERNO, SEM SIMILAR NACIONAL, CONSTANTE EM LISTA DE RESOLUÇÃO CAMEX E GÁS NATURAL.');
INSERT INTO `origem_cst` VALUES ('9', '8', 'NACIONAL, MERCADORIA OU BEM COM CONTEÚDO DE IMPORTAÇÃO SUPERIOR A 70%.');
